[build.environment]
  NODE_VERSION = "18"
  DISABLE_IPX = "true"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
[[headers]]
  for = "/*.webp?*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
